import { Poppins } from 'next/font/google'
import "..//styles/globals.css";
import { SectionsProvider } from "@/context/SectionsContext"; // adjust path

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins'
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <SectionsProvider>
          {children}
        </SectionsProvider>
      </body>
    </html>
  );
}
